"""Type stubs for delta_fusion."""

from typing import Any

class DeltaEngine:
    """High-performance Delta Lake query engine."""

    def __init__(self, storage_options: dict[str, Any] | None = None) -> None: ...
    def register_table(
        self, name: str, path: str, version: int | None = None
    ) -> None: ...
    def refresh_table(self, name: str) -> None: ...
    def refresh_all(self) -> None: ...
    def deregister_table(self, name: str) -> None: ...
    def query(self, sql: str) -> list[Any]: ...
    def query_to_dicts(self, sql: str) -> list[dict[str, Any]]: ...
    def table_info(self, name_or_path: str) -> dict[str, Any]: ...
    def list_tables(self) -> list[str]: ...
    def is_registered(self, name: str) -> bool: ...
